### ISSUE TITLE
フィードバックフォーム設置

### ISSUE THREAD

**Issue by naichilab** [naichilab/lets-play-mobile-games#10]
https://docs.google.com/forms/d/e/1FAIpQLSfEta48PsfTBTkIx76idPpI7yNzo_HTdg-RknYm1ZxhGh7gWw/viewform
このURLへのリンクを埋め込む

参考サイト
https://marshmallow-qa.com/

**Comment by pafumo** [comment]
リンク先に飛ばすために【ご意見要望は"こちら"】みたいな感じでどこかに表示すると思うんですが、どのページのどこに表示させるかは決まってますかね？

**Comment by naichilab** [comment]
ヘッダーのゲーム登録の右ぐらいでいいんでないかな。レイアウトは崩れるかもだけど。
