### ISSUE TITLE
確認メールが英語でわかりづらい

### ISSUE THREAD

**Issue by naichilab** [naichilab/lets-play-mobile-games#17]
![2017-12-02 1 51 09](https://user-images.githubusercontent.com/7110482/33493453-6674f58e-d703-11e7-9764-0babb9a771cc.png)

**Comment by Subarunari** [comment]
config/locale/devise.ja.ymlを追加して対応しようと思います。それに伴い、devise.en.ymlをデフォに戻しますー

**Comment by naichilab** [comment]
おねがいしまーす
なんでかローカルでjaリソース追加しても反映できなくて無理やりやった気がします。全体的に見直してもらえると助かります。
