### ISSUE TITLE
githubのREADME書く

### ISSUE THREAD

**Issue by naichilab** [naichilab/lets-play-mobile-games#19]

**Comment by naichilab** [comment]
とりあえず書いときたい内容

サイト概要
お手伝いさんを募集していること
    issueやプルリク歓迎
開発環境の構築方法
ライセンス表記

**Comment by pafumo** [comment]
ライセンス表記ってなに書くんでしょ？

**Comment by naichilab** [comment]
https://qiita.com/shibukk/items/67ad0a5eda5a94e5c032
この辺。まぁどれにするかもちゃんと決めてないんだけど。

**Comment by pafumo** [comment]
なるほど。適当に決めておくので、固まって来たら話し合いましょう！

**Comment by pafumo** [comment]
---未実装箇所---
・ライセンスの記述
・sampleファイル用意するのであれば文章の改変

**Comment by naichilab** [comment]
これ、クローズしちゃおうか。
今のままでしばらくいいっしょ。

**Comment by pafumo** [comment]
作るものが明確になったら立てますか〜
