### ISSUE TITLE
編集画面に画像が出ていて欲しい

### ISSUE THREAD

**Issue by naichilab** [naichilab/lets-play-mobile-games#2]
投稿済みのを編集しようとすると、設定した画像が外れて見える（実際は編集確定しても大丈夫）のがちょっとヒヤッとしました

**Comment by naichilab** [comment]
編集時に今の画像が出てるとよい。

**Comment by Subarunari** [comment]
これってゲーム編集画面ですかね？であれば、 #102 対応時にいつの間にかクリアしてしまっている気がする。

**Comment by naichilab** [comment]
ですね！クローズで！
