### ISSUE TITLE
スマホレイアウト崩れ

### ISSUE THREAD

**Issue by naichilab** [naichilab/lets-play-mobile-games#4]
iphone seの幅だとハンバーガーメニューが段落ちしてしまってソーシャルボタンがヘッダーにめり込む

![image](https://user-images.githubusercontent.com/7110482/33332200-f38ee664-d4a6-11e7-9e8e-ac5fefad639d.png)

**Comment by Subarunari** [comment]
これ着手します。
ヘッダの段がずれるのとゲーム一覧画面でアイコンとタイトルがかぶるのをそれぞれ修正します。
