### ISSUE TITLE
TOP以外も全部同じタイトルになってる

### ISSUE THREAD

**Issue by naichilab** [naichilab/lets-play-mobile-games#51]

**Comment by pafumo** [comment]
これどういうバグなのでしょ？
ぱっと見わからないんですが...

**Comment by naichilab** [comment]
![2017-12-17 20 10 41](https://user-images.githubusercontent.com/7110482/34078927-685f27ec-e366-11e7-8286-6442230a46f6.png)

どの画面開いても同じタイトル（htmlのtitleタグ）になってる。（今はゲーム一覧だけは変更済み）
titleはgoogle検索結果にも出るので、ページごとに正しくつけるべき。

**Comment by pafumo** [comment]
あぁーなるほど！気づかなかった...!
どうもですー

**Comment by pafumo** [comment]
#38 のPR通ってませんが次いって良いのですかね？
良ければこいついただきます〜。

**Comment by naichilab** [comment]
いいすよー
