### ISSUE TITLE
ユーザー名の表示と変更

### ISSUE THREAD

**Issue by naichilab** [naichilab/lets-play-mobile-games#61]
* ログイン後ヘッダーの `プロフィール変更` のテキストをユーザー名にする？
* プロフィール変更画面で `ユーザー名` を変更可能にする

**Comment by Subarunari** [comment]
<img width="1010" alt="default" src="https://user-images.githubusercontent.com/8957958/34066899-c3d876d0-e25a-11e7-8b3e-67df8a775d1c.png">

こんな感じでユーザ関連作業はまとめちゃうのもありかなーと思いました。ゲーム登録もすべてのユーザにとって必要ではなく、頻度としてはあまり多くないと思うので、同じ枠に納めてもいいかもしれません。

**Comment by naichilab** [comment]
まとめたいけどCSSわかんない状態でした！！まとめたいです！！

**Comment by Subarunari** [comment]
じゃあ次はこれ食べ始めます！！
