### ISSUE TITLE
ツイートボタンからのツイートメッセージ、サイト名が古い

### ISSUE THREAD

**Issue by naichilab** [naichilab/lets-play-mobile-games#72]
## 期待する動作

ツイートボタン押下時、
「ゲームを実況しよう！ http://letsplaylist.genieus.co.jp/ 」と表示される。

## 実際の動作

「そのゲーム、実況できる？ http://letsplaylist.genieus.co.jp/ 」と表示されている。

## 再現手順

  1. TOPにアクセス
  1. ツイートボタンを押す

**Comment by Subarunari** [comment]
localeファイルにサイト名を表す値を設定し、TOPページもTweetボタンもその値から取得したほうが良い気がしました。また変わるとき2重修正忘れそうなので・・・。

**Comment by naichilab** [comment]
たしかに。。。

**Comment by pafumo** [comment]
@Subarunari こいつ食おうと思うんですが、ロケールファイルに各地域ごとのサイト名定義しておいて代入する感じで良いのですかね？
