### ISSUE TITLE
説明文中のURLをリンクにしたい

### ISSUE THREAD

**Issue by naichilab** [naichilab/lets-play-mobile-games#78]
## 期待する動作

ガイドライン等に含まれるURLがリンクになる

## 実際の動作

テキスト表示になってる。

> ref. https://letsplaylist.genieus.co.jp/games/18

**Comment by Subarunari** [comment]
サーバサイドで対応するならこれでできそう
 https://qiita.com/satoken0417/items/df4098a122d05d69a3e6
