### ISSUE TITLE
bootstrap v3 to v4

### ISSUE THREAD

**Issue by Subarunari** [naichilab/lets-play-mobile-games#91]
## 期待する動作
* bootstrap v4が導入されており、レイアウトが崩れていない

## 詳細
* スタイル崩れが予想されます。全画面のチェックする
* classが変わってるものものあるので、それも対応する
* v4によりBootstrapのSassを使えるようになるので、それに合わせて既存のsassをリファクタリングする

**Comment by naichilab** [comment]
sassが使えるっていうのは、bootstrapで定義してある変数が自分のsassに取り込んで使えるってことです？

**Comment by Subarunari** [comment]
ちゃんと見てみないとわかりませんがおそらく！どうせ使うなら早い方がいいと思うんでこれはじめようと思いますー。

**Comment by Subarunari** [comment]
まだBetaでした・・・必ず必要というわけではないのでBetaが取れてからやろうと思います

**Comment by Subarunari** [comment]
ぼちぼち始めようと思います https://getbootstrap.com/
