### ISSUE TITLE
リンクテキストはデコードしたい気がする

### ISSUE THREAD

**Issue by naichilab** [naichilab/lets-play-mobile-games#98]
## 期待する動作

* https://letsplaylist.genieus.co.jp/games/1
* iOSリンク先URLに日本語が含まれているが、エンコードされて長い文字列になってる
    * 表示
 `https://itunes.apple.com/jp/app/%E5%A4%AA%E9%99%BD%E4%BA%BA%E9%96%93/id1195337640?mt=8`
    * ブラウザでの表示 `https://itunes.apple.com/jp/app/太陽人間/id1195337640?mt=8`

## 実際の動作

* デコードされたテキストを表示したい

## その他

* URIエンコードの逆を行うライブラリあるかな？

**Comment by Subarunari** [comment]
https://docs.ruby-lang.org/ja/latest/class/URI.html
URI.unescapeはもうObsoleteになっているようなので、CGI.unescape使うのが良さそうですね。link_to の文字列部分だけCGI.unescapeかかるようなヘルパー作っても良さそう
